import React from 'react';

export default React.createContext({
    user: "",
    token: "",
    showHeader: true,
    messages: [],
    assets: [],
    assetValueHist: [],
    cookies: {},
    favoriteAssets: [],
    date: "",
    integrationToken: "",
    orders: [],
    sectorExposures: [],
    portfolios: [],
    setUser: (newUser) => { },
    setToken: (newToken) => { },
    setShowHeader: (newShowHeader) => { },
    setMessages: (newMessages) => { },
    setCookies: (cookieName, cookieValue) => { },
    removeCookies: (cookieName) => { },
    setAssets: (newAssets) => { },
    setAssetValueHist: (newAssetValueHist) => { },
    setFavoriteAssets: (newFavoriteAssets) => { },
    switchDate: (newDate) => { },
    setOrders: (newOrders) => { },
    setPortfolios: (newPortfolios) => { },
    setSectorExposures: (newSectorExposures) => { }
});